### ISSUE TITLE
Rollup failed to resolve @vue/composition-api when upgrading to @egjs/flicking@4.14.0

### ISSUE THREAD

**Issue by vietanhdang** [naver/egjs-flicking#929]
### Environment
- **@egjs/flicking**: 4.14.0  
- **Build tool**: Vite 4.3.5 
- **Framework**: Vue 2.17.4
- **Related package**: `@cfcs/vue2`  
- **Node version**: NodeJs16
- **OS**: Linux (running on Jenkins CI)

### Describe the bug
After upgrading to `@egjs/flicking@4.14.0`, the Vite build fails due to a Rollup resolution error. The error message suggests that the `@vue/composition-api` module cannot be resolved when used by `@cfcs/vue2`.

### Build error
```
Rollup failed to resolve import "@vue/composition-api" from "/jenkins/.../node_modules/@cfcs/vue2/dist/cfcs.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to `build.rollupOptions.external`
```

### Steps to reproduce
1. Use a Vue 2
2. Install `@egjs/flicking@4.14.0`
3. Build the project using Vite
4. Observe the Rollup error

### Expected behavior
The Vite build should succeed without needing manual configuration for `@vue/composition-api`.

### Additional context
- Reverting to an earlier version of `@egjs/flicking` resolves the build issue.
- It seems the dependency on `@vue/composition-api` is introduced via `@cfcs/vue2` and is not being handled correctly by Rollup in Vite.
- Suggest checking if the package should declare `@vue/composition-api` as a `peerDependency` or be properly bundled/externalized.

**Comment by vietanhdang** [comment]
> Same issue here with the same stack as [@vietanhdang](https://github.com/vietanhdang). After upgrading from v4.13.0 to v4.14.0:
> 
> ```
> └─┬ @egjs/vue-flicking@4.14.0
>   └── @cfcs/vue2@0.1.1
> ```
> 
> The @cfcs/vue2 package appears to be at version 0.1.1, but the build error persists:
> 
> ✘ [ERROR] No matching export in "node_modules/@egjs/vue-flicking/node_modules/vue/dist/vue.runtime.esm.js" for import "reactive"
> 
>     node_modules/@egjs/vue-flicking/node_modules/@cfcs/vue2/dist/cfcs.esm.js:11:9:
>       11 │ import { reactive } from 'vue';
>          ╵          ~~~~~~~~
> 
> /<>/node_modules/esbuild/lib/main.js:1467
>   let error = new Error(text);
>               ^
> 
> Error: Build failed with 1 error:
> node_modules/@egjs/vue-flicking/node_modules/@cfcs/vue2/dist/cfcs.esm.js:11:9: ERROR: No matching export in "node_modules/@egjs/vue-flicking/node_modules/vue/dist/vue.runtime.esm.js" for import "reactive"
>     at failureErrorWithLog (/<>/node_modules/esbuild/lib/main.js:1467:15)
>     at /<>/node_modules/esbuild/lib/main.js:926:25
>     at /<>/node_modules/esbuild/lib/main.js:1345:9
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
>   errors: [Getter/Setter],
>   warnings: [Getter/Setter]
> }

I have resolved this issue by using version 4.10.7 of @egjs/vue-flicking instead of the ^version.

**Comment by francoistomasi** [comment]
I forced version 4.13.0, and it’s working.
